Goals section
IrinaSing/Readeer pull request #48
Opened 2021-11-01 14:59 UTC by sheybusta

Here's goals section

2021-11-01 15:55 UTC, erkamguresen requested changes
- branch is out of date. it needs a rebase or merge
- there are merge conflicts
- looks out of place in mobile (iphone 6,7,8)
- is the goals section justified to both sides or should be in center? (I am not sure about the design)

2021-11-02 08:03 UTC, IrinaSing commented
Hi @sheybusta there are some tutorials that help to make responsive layout with bootstrap

- https://youtu.be/1v_XcJsGtyA

- https://youtu.be/4sosXZsdy-s

2021-11-02 20:08 UTC, erkamguresen approved these changes

2021-11-02 20:55 UTC, IrinaSing approved these changes

2021-11-02 20:55 UTC, merged