Offer-btn-rebase
IrinaSing/Readeer pull request #66
Opened 2021-11-07 22:55 UTC by Fatihayoz

---
name: code review PR
about: A template PR for contributing to this project
---

## Checklists

- [ ] All CI checks pass
- [ ] The branch works when you pull it and run it locally

... anything else your group would like to add to the checklist?

2021-11-08 12:04 UTC, IrinaSing commented
Hi @Fatihayoz There are few console log statements, do you still want to use them?

2021-11-08 16:30 UTC, erkamguresen commented
> Hi @Fatihayoz There are few console log statements, do you still want to use them?

@IrinaSing I will work on the branch...

2021-11-08 16:30 UTC, erkamguresen requested changes
page refresh is not compleated
console logs should be deleted

2021-11-12 08:11 UTC, erkamguresen approved these changes

2021-11-12 10:20 UTC, IrinaSing approved these changes

2021-11-12 10:20 UTC, merged